Vagrant.configure("2") do |config|
  config.vm.box = "generic/rhel7"
  config.vm.synced_folder "/Users/alex/git/redhat/hmrc", "/home/vagrant/hmrc"

  config.vm.provider :virtualbox do |v|
    v.name = "rhel7.dev"
    v.memory = 2048
    v.cpus = 2
  end

  if Vagrant.has_plugin?('vagrant-registration')
    config.registration.manager = 'subscription_manager'
    config.registration.auto_attach = true
    config.registration.username = ENV['RH_USER']
    config.registration.password = ENV['RH_PASS']
  end

  config.vm.provision :ansible do |ansible|
    #ansible.verbose = "vvv"
    #ansible.extra_vars = { "ansible_python_interpreter" => "/usr/bin/python2" }
    ansible.playbook = "provisioning/main.yml"
  end
end
